base/urls.py
import environ
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from users.views import LogoutUser, NewUserRegister, UserProfile

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env()

DEBUG = env("DEBUG")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("machines.urls")),
    path("", include("tools_assembly.urls")),
    path("", include("tools.urls")),
    path("", include("holders.urls")),
    path("", include("notifications.urls")),
    path("register/", NewUserRegister.as_view(), name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", LogoutUser.as_view(), name="logout"),
    path("profile/", UserProfile.as_view(), name="profile"),
    path("i18n/", include("django.conf.urls.i18n")),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

tools_assembly/urls.py
from django.urls import path

from .views import (
    ToolAssemblyAddCommentView,
    ToolAssemblyCreateView,
    ToolAssemblyDeleteView,
    ToolAssemblyDetailView,
    ToolAssemblyListView,
    ToolAssemblyUpdateView,
)

urlpatterns = [
    path(
        "tool-assembly/new/",
        ToolAssemblyCreateView.as_view(),
        name="tool-assembly-create",
    ),
    path("tool-assembly/", ToolAssemblyListView.as_view(), name="tool-assembly"),
    path(
        "tool-assembly/<int:pk>/",
        ToolAssemblyDetailView.as_view(),
        name="tool-assembly-detail",
    ),
    path(
        "tool-assembly/<int:pk>/delete/",
        ToolAssemblyDeleteView.as_view(),
        name="tool-assembly-delete",
    ),
    path(
        "tool-assembly/<int:pk>/update/",
        ToolAssemblyUpdateView.as_view(),
        name="tool-assembly-update",
    ),
    path(
        "tool-assembly/<int:pk>/add-comment/",
        ToolAssemblyAddCommentView.as_view(),
        name="add-comment",
    ),
]

holders/models.py
from django.contrib.auth.models import User
from django.db import models


class Holder(models.Model):
    holder_type_choices = [
        ("type_1", "SLIM_100"),
        ("type_2", "SLIM_150"),
        ("type_3", "SLIM_200"),
        ("type_4", "TERMO_100"),
        ("type_5", "TERMO_150"),
        ("type_6", "TERMO_200"),
        ("type_7", "ER_32"),
        ("type_8", "ER_40"),
        ("type_9", "WELDON_100"),
        ("type_10", "WELDON_150"),
        ("type_11", "WELDON_200"),
        ("type_12", "STYROPIAN"),
        ("type_13", "UCHWYT_76"),
    ]

    holder_type_dict = dict(holder_type_choices)

    holder_type = models.CharField(max_length=100, choices=holder_type_choices, help_text="Holder type")
    inner_diameter = models.PositiveIntegerField(help_text="Inner diameter of the holder")
    catalog_nr = models.CharField(max_length=100, blank=True, help_text="Holder catalog number")
    LH1 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the first holder segment"
    )
    DH1_A = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        blank=True,
        null=True,
        help_text="First outside diameter of the first holder segment",
    )
    DH1_B = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        blank=True,
        null=True,
        help_text="Second outside diameter of the first holder segment",
    )
    LH2 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the second holder segment"
    )
    DH2 = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        blank=True,
        null=True,
        help_text="Outside diameter of the second holder segment",
    )
    LH3 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the third holder segment"
    )
    DH3 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Outside diameter of the third holder segment"
    )
    author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=None, help_text="Author of the holder")

    def __str__(self):
        return self.holder_type_dict.get(self.holder_type, "Unknown holder type")

tools/models.py
from django.contrib.auth.models import User
from django.db import models


class Tool(models.Model):
    tool_type_choices = [
        ("end_mill", "WALEC"),
        ("ball_nose", "KULA"),
        ("bull_nose", "WALEC_Z_R"),
        ("typer_ball_nose", "STOZKOWY"),
        ("engraving", "GRAWERKA"),
        ("drill", "WIERTŁO"),
    ]

    tool_type_dict = dict(tool_type_choices)

    tool_type = models.CharField(max_length=100, choices=tool_type_choices, help_text="Tool type")
    catalog_nr = models.CharField(max_length=100, help_text="Tool catalog number")
    R = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Corner radius of a end- and bull- mill"
    )
    L1 = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True, help_text="Blade length")
    D1 = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True, help_text="Blade diameter")
    L2 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the first shaft segment"
    )
    D2 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Diameter of the first shaft segment"
    )
    L3 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the second shaft segment"
    )
    D3 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Diameter of the second shaft segment"
    )
    L4 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the third shaft segment"
    )
    D4 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Diameter of the third shaft segment"
    )
    author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=None, help_text="Author of the tool")

    def __str__(self):
        return self.tool_type_dict.get(self.tool_type, "Unknown tool type")

tools_assembly/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from holders.models import Holder
from machines.models import Machine
from tools.models import Tool


class ToolAssembly(models.Model):
    tool_nr = models.PositiveIntegerField(help_text="Number of the tool assembly in machine table.")
    radius = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Radius of the tool assembly."
    )
    total_length = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True, help_text="Total tool length."
    )
    outside_holder = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True, help_text="Length outside the holder."
    )
    machine = models.ForeignKey(
        Machine,
        on_delete=models.SET_DEFAULT,
        default=None,
        related_name="tools",
        null=True,
        help_text="The machine to which the tool is assigned.",
    )
    holder = models.ForeignKey(
        Holder, on_delete=models.CASCADE, help_text="A holder component used in a tool assembly."
    )
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE, help_text="A tool component used in a tool assembly.")
    author = models.ForeignKey(
        User,
        on_delete=models.SET_DEFAULT,
        default=None,
        help_text="Author of the tool assembly.",
    )

    def get_comments(self):
        return self.comments.order_by("-date_posted")


class UserComment(models.Model):
    content = models.TextField(help_text="User comment.")
    date_posted = models.DateTimeField(
        default=timezone.now, help_text="Date the comment was published <em>YYYY-MM-DD</em>."
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, help_text="Author of the user comment.")
    tool_assembly = models.ForeignKey(
        ToolAssembly,
        on_delete=models.CASCADE,
        related_name="comments",
        help_text="The tool assembly to which the comment is assigned.",
    )

tools_assembly/views.py
import logging
from typing import Dict, List, Type, Union

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .forms import ToolAssemblyForm, ToolAssemblySlim, UserCommentForm
from .models import ToolAssembly, UserComment

logger = logging.getLogger(__name__)
Breadcrumb = Dict[str, Union[str, str]]


class BreadcrumbMixin:
    def get_context_data(self, **kwargs) -> Dict[str, Union[str, List[Breadcrumb]]]:
        context = super().get_context_data(**kwargs)
        context["breadcrumbs"] = self.get_breadcrumbs()
        return context

    def get_breadcrumbs(self) -> List[Breadcrumb]:
        breadcrumbs = [{"title": "Strona główna", "url": reverse("app-home")}]

        if isinstance(self, ToolAssemblyListView):
            breadcrumbs.append({"title": "Tabela narzędzi", "url": reverse("tool-assembly")})
        elif isinstance(self, ToolAssemblyDetailView):
            assembly = self.get_object()
            breadcrumbs.append({"title": "Tabela narzędzi", "url": reverse("tool-assembly")})
            breadcrumbs.append(
                {
                    "title": f"Narzędzie numer: {assembly.tool_nr}",
                    "url": reverse("tool-assembly-detail", kwargs={"pk": assembly.pk}),
                }
            )
        elif isinstance(self, ToolAssemblyCreateView):
            breadcrumbs.append({"title": "Utwórz nowe narzędzie", "url": reverse("tool-assembly-create")})
        elif isinstance(self, ToolAssemblyUpdateView):
            assembly = self.get_object()
            breadcrumbs.append({"title": "Tabela narzędzi", "url": reverse("tool-assembly")})
            breadcrumbs.append(
                {
                    "title": "Aktualizuj narzędzie",
                    "url": reverse("tool-assembly-update", kwargs={"pk": assembly.pk}),
                }
            )

        return breadcrumbs


class ToolAssemblyCreateView(BreadcrumbMixin, LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    permission_required = "tools_assembly.add_toolassembly"
    model = ToolAssembly
    template_name = "tools_assembly/tool_assembly_form.html"
    form_class = ToolAssemblyForm
    success_url = reverse_lazy("tool-assembly")

    def form_valid(self, form: ToolAssemblyForm) -> HttpResponse:
        form.instance.author = self.request.user
        logger.info(f"Tool assembly nr: {form.instance.tool_nr} created by user {form.instance.author}.")
        return super().form_valid(form)


class ToolAssemblyListView(BreadcrumbMixin, ListView):
    model = ToolAssembly
    template_name = "tools_assembly/tool_assembly.html"

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        user = request.user
        logger.info(f"Tool assembly List View accessed by user {user}")
        return super().get(request, *args, **kwargs)


class ToolAssemblyDetailView(BreadcrumbMixin, DetailView):
    model = ToolAssembly
    template_name = "tools_assembly/tool_assembly_detail.html"

    def get_context_data(self, **kwargs) -> Dict[str, Union[str, List[Breadcrumb], UserCommentForm]]:
        context: Dict[str, Union[str, List[Breadcrumb], UserCommentForm]] = super().get_context_data(**kwargs)
        context["comment_form"] = UserCommentForm()
        return context

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        tool_assembly = self.get_object()
        user = request.user
        logger.info(f"Tool assembly nr: {tool_assembly.tool_nr} Detail View accessed by user {user}")
        return super().get(request, *args, **kwargs)


class ToolAssemblyDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = "tools_assembly.delete_toolassembly"
    model = ToolAssembly
    template_name = "tools_assembly/tool_assembly_delete_confirm.html"
    success_url = "/"

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        tool_assembly = self.get_object()
        user = request.user
        logger.info(f"Tool assembly nr: {tool_assembly.tool_nr} deleted by user {user}")
        return super().post(request, *args, **kwargs)


class ToolAssemblyUpdateView(BreadcrumbMixin, LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = "tools_assembly.change_toolassembly"
    model = ToolAssembly
    template_name = "tools_assembly/tool_assembly_form.html"

    def get_form_class(self) -> Type[Union[ToolAssemblySlim, ToolAssemblyForm]]:
        if self.request.user.groups.filter(name="Operator").exists():
            return ToolAssemblySlim
        return ToolAssemblyForm

    def get_success_url(self) -> str:
        return reverse("tool-assembly-detail", kwargs={"pk": self.object.pk})

    def form_valid(self, form: Union[ToolAssemblySlim, ToolAssemblyForm]) -> HttpResponse:
        form.instance.author = self.request.user
        logger.info(f"Tool assembly nr: {form.instance.tool_nr} updated by {form.instance.author}.")
        return super().form_valid(form)


class UserCommentListView(ListView):
    model = UserComment
    context_object_name = "comments"
    ordering = ["-date_posted"]
    paginate_by = 10


class ToolAssemblyAddCommentView(View):
    def post(self, request: HttpRequest, pk: int) -> HttpResponse:
        tool_assembly = get_object_or_404(ToolAssembly, pk=pk)
        comment_form = UserCommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.author = request.user
            new_comment.tool_assembly = tool_assembly
            new_comment.save()

        logger.info(f"New comment add to tool assembly nr: {tool_assembly.tool_nr} by {request.user}.")

        return redirect("tool-assembly-detail", pk=pk)

tools_assembly/templates/tools_assembly/tool_assembly.html
{% extends "machines/index.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="container">
    <div class="col-lg text-center">
        <img src="{% static 'media/tool.jpg' %}" alt="Tool Image" class="img-fluid rounded" width="500" height="auto">
    </div>
    <div class="row justify-content-center">
        <div class="col-lg">
            {% if perms.tools_assembly.add_toolassembly %}
            <div class="text-end mb-3">
                <a class="btn btn-secondary btn-md mt-5 mb-0" href="{% url 'tool-assembly-create' %}">{% blocktrans %} Add new tool assembly {% endblocktrans %}</a>
            </div>
            {% endif %}
            <div class="card shadow-lg border-0 rounded-lg mt-3">
                <div class="card mb-4">
                    <div class="card-header">
                        <i class="fas fa-table me-1"></i>
                        {% blocktrans %} Table of tools assembly {% endblocktrans %}
                    </div>
                    <div class="card-body">
                        <table id="datatablesSimple">
                            <thead>
                                <tr>
                                    <th>{% blocktrans %} Tool assembly nr {% endblocktrans %}</th>
                                    <th>{% blocktrans %} Radius {% endblocktrans %}</th>
                                    <th>{% blocktrans %} Total length {% endblocktrans %}</th>
                                    <th>{% blocktrans %} Outside holder {% endblocktrans %}</th>
                                    <th>{% blocktrans %} Machine {% endblocktrans %}</th>
                                    <th>{% blocktrans %} Holder type {% endblocktrans %}</th>
                                    <th>{% blocktrans %} Tool type {% endblocktrans %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for tool_assembly in object_list %}
                                <tr>
                                    <td><a href="{% url 'tool-assembly-detail' tool_assembly.pk %}">{{ tool_assembly.tool_nr }}</a></td>
                                    <td>{{ tool_assembly.radius }}</td>
                                    <td>{{ tool_assembly.total_length }}</td>
                                    <td>{{ tool_assembly.outside_holder }}</td>
                                    <td>{{ tool_assembly.machine.name }}</td>
                                    <td>{{ tool_assembly.holder.get_holder_type_display }}</td>
                                    <td>{{ tool_assembly.tool.get_tool_type_display }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#tool_assembly').DataTable({
        "paging": true,
        "ordering": true,
        "info": true
    });
});
</script>
{% endblock content %}

tools_assembly/templates/tools_assembly/tool_assembly_delete_confirm.html
{% extends "machines/index.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-left font-weight-light my-4">{% blocktrans %} Delete tool assembly {% endblocktrans %}</h3></div>
                <div class="content-section">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset class="form group">
                                <h3>{% blocktrans %} Are you sure you want to delete tool assembly {{ object.tool_nr }} with radius: {{ object.radius }} mm? {% endblocktrans %}</h3>
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-danger" type="submit">{% trans "Yes" %}</button>
                                <a class="btn btn-secondary" href="{% url 'tool-assembly-detail' object.id %}">{% trans "Cancel" %}</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

tools_assembly/templates/tools_assembly/tool_assembly_detail.html
{% extends "machines/index.html" %}
{% load i18n %}
{% load static %}
{% block content %}
<div class="container">
    <div class="col-lg text-center">
        <img src="{% static 'media/tool.jpg' %}" alt="Tool Image" class="img-fluid rounded" width="500" height="auto">
    </div>
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header ">
                    {% if perms.tools_assembly.change_toolassembly %}
                    <h4 class="text-end mt-4">
                    <a class="btn btn-secondary btn-sm mt-1 mb-1 " href="{% url 'tool-assembly-update' object.id %}">{% trans "Edit" %}</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1 " href="{% url 'tool-assembly-delete' object.id %}">{% trans "Delete" %}</a>
                    </h4>
                    {% endif %}
                </div>
                <div class="content-section">
                    <div class="card-body">
                        <div class="row mb-3">
                            <div class="col">
                                <strong>{% trans "Tool assembly nr: " %}</strong> {{ object.tool_nr }}
                            </div>
                            <div class="col">
                                <strong>{% trans "Radius: " %}</strong> {{ object.radius }}
                            </div>
                            <div class="col">
                                <strong>{% trans "Total length: " %}</strong> {{ object.total_length }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col">
                                <strong>{% trans "Outside holder: " %}</strong> {{ object.outside_holder }}
                            </div>
                            <div class="col">
                                <strong>{% trans "Machine" %}</strong> {{ object.machine }}
                            </div>
                            <div class="col">
                                <strong>{% trans "Holder type: " %}</strong> {{ object.holder.get_holder_type_display }}
                            </div>
                        </div>
                        <div class="row mb-3">
                            <div class="col">
                                <strong>{% trans "Tool type: " %}</strong> {{ object.tool.get_tool_type_display }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header ">
                    <h4 class="text">{% trans "Comments" %}</h4>
                </div>
                <div class="content-section">
                    <div class="card-body">
                        <div class="row mb-3">
                            <form method="post" action="{% url 'add-comment' object.pk %}">
                                <a class="row mb-3">
                                <button type="submit" class="btn btn-secondary btn-sm mt-1 mb-1">{% trans "Add comment" %}</button>
                                </a>
                                <div class="row mb-3">
                                    {% csrf_token %}
                                    {{ comment_form.content }}
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row mb-3">
                            {% for comment in object.get_comments %}
                                <article class="media content-section">
                                    <div class="media-body">
                                        <div class="article-metadata">
                                            <a class="mr-2" href="{% url 'profile' %}">{{ comment.author }}</a>
                                            <small class="text-muted">{{ comment.date_posted }}</small>
                                        </div>
                                        <p class="article-content"><i>{{ comment.content }}</i></p>
                                    </div>
                                </article>
                            {% endfor %}
                            {% if page_obj.has_previous %}
                                <div class="col-md-12 mb-4">
                                    <a class="btn btn-outline-info" href="?page=1">First</a>
                                    <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
                                </div>
                            {% endif %}
                            <div class="col-md-12 mb-4">
                                {% for num in page_obj.paginator.page_range %}
                                    {% if page_obj.number == num %}
                                        <a class="btn btn-info" href="?page={{ num }}">{{ num }}</a>
                                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                        <a class="btn btn-outline-info" href="?page={{ num }}">{{ num }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                            {% if page_obj.has_next %}
                                <div class="col-md-12 mb-4">
                                    <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
                                    <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">{% trans "Last" %}</a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

tools_assembly/templates/tools_assembly/tool_assembly_form.html
{% extends "machines/index.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container">
    <div class="col-lg text-center">
        <img src="{% static 'media/tool.jpg' %}" alt="Tool Image" class="img-fluid rounded" width="500" height="auto">
    </div>
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header">
                    <h3 class="text-left font-weight-light my-4">{% trans " " %}</h3>
                </div>
                <div class="content-section">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% if form.errors %}
                            <div class="alert alert-danger">
                                <strong>{% trans "Invalid data entered: " %}</strong>
                                <ul>
                                    {% for field, errors in form.errors.items %}
                                    {% for error in errors %}
                                    <li>{{ error }}</li>
                                    {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                            {% endif %}
                            <div class="row mb-3">
                                    <fieldset class="form-group">
                                        <div class="row mb-3">
                                            <div class="col">
                                                <strong>{{ form.tool_nr.label_tag }}</strong> {{ form.tool_nr }}
                                            </div>
                                            <div class="col">
                                                <strong>{{ form.radius.label_tag }}</strong> {{ form.radius }}
                                            </div>
                                            <div class="col">
                                                <strong>{{ form.total_length.label_tag }}</strong> {{ form.total_length }}
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>

                            <div class="row mb-3">
                                    <fieldset class="form-group">
                                        <div class="row mb-3">
                                            <div class="col">
                                                <strong>{{ form.outside_holder.label_tag }}</strong> {{ form.outside_holder }}
                                            </div>
                                            <div class="col">
                                                <strong>{{ form.machine.label_tag }}</strong> {{ form.machine }}
                                            </div>
                                            <div class="col">
                                                <strong>{{ form.holder.label_tag }}</strong> {{ form.holder }}
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>
                            <div class="row mb-3">
                                    <fieldset class="form-group">
                                        <div class="row mb-3">
                                            <div class="col">
                                                <strong>{{ form.tool.label_tag }}</strong> {{ form.tool }}
                                            </div>
                                        </div>
                                    </fieldset>
                                </div>
                            <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                <button class="btn btn-primary" type="submit">{% trans "Save" %}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}