base/urls.py
import environ
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from users.views import LogoutUser, NewUserRegister, UserProfile

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env()

DEBUG = env("DEBUG")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("machines.urls")),
    path("", include("tools_assembly.urls")),
    path("", include("tools.urls")),
    path("", include("holders.urls")),
    path("", include("notifications.urls")),
    path("register/", NewUserRegister.as_view(), name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", LogoutUser.as_view(), name="logout"),
    path("profile/", UserProfile.as_view(), name="profile"),
    path("i18n/", include("django.conf.urls.i18n")),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

machines/urls.py
from django.urls import path

from .views import (  # generic_pdf,
    MachineCreateView,
    MachineDeleteView,
    MachineDetailView,
    MachineUpdateView,
    generate_csv,
    home,
)

urlpatterns = [
    path("", home, name="app-home"),
    path("machine/<int:pk>/", MachineDetailView.as_view(), name="machine-detail"),
    path("machine/new/", MachineCreateView.as_view(), name="machine-create"),
    path("machine/<int:pk>/update/", MachineUpdateView.as_view(), name="machine-update"),
    path("machine/<int:pk>/delete/", MachineDeleteView.as_view(), name="machine-delete"),
    path("tools/generate-csv/", generate_csv, name="generate-csv"),
    # path("tools/generate-pdf/", generic_pdf, name="generate-pdf"),
]

tool_manager/machines/urls.py
from django.urls import path

from .views import (
    MachineCreateView,
    MachineDeleteView,
    MachineDetailView,
    MachineUpdateView,
    generate_csv,
    generic_pdf,
    home,
)

urlpatterns = [
    path("", home, name="app-home"),
    path("machine/<int:pk>/", MachineDetailView.as_view(), name="machine-detail"),
    path("machine/new/", MachineCreateView.as_view(), name="machine-create"),
    path("machine/<int:pk>/update/", MachineUpdateView.as_view(), name="machine-update"),
    path("machine/<int:pk>/delete/", MachineDeleteView.as_view(), name="machine-delete"),
    path("tools/generate-csv/", generate_csv, name="generate-csv"),
    path("tools/generate-pdf/", generic_pdf, name="generate-pdf"),
]

holders/models.py
from django.contrib.auth.models import User
from django.db import models


class Holder(models.Model):
    holder_type_choices = [
        ("type_1", "SLIM_100"),
        ("type_2", "SLIM_150"),
        ("type_3", "SLIM_200"),
        ("type_4", "TERMO_100"),
        ("type_5", "TERMO_150"),
        ("type_6", "TERMO_200"),
        ("type_7", "ER_32"),
        ("type_8", "ER_40"),
        ("type_9", "WELDON_100"),
        ("type_10", "WELDON_150"),
        ("type_11", "WELDON_200"),
        ("type_12", "STYROPIAN"),
        ("type_13", "UCHWYT_76"),
    ]

    holder_type_dict = dict(holder_type_choices)

    holder_type = models.CharField(max_length=100, choices=holder_type_choices, help_text="Holder type")
    inner_diameter = models.PositiveIntegerField(help_text="Inner diameter of the holder")
    catalog_nr = models.CharField(max_length=100, blank=True, help_text="Holder catalog number")
    LH1 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the first holder segment"
    )
    DH1_A = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        blank=True,
        null=True,
        help_text="First outside diameter of the first holder segment",
    )
    DH1_B = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        blank=True,
        null=True,
        help_text="Second outside diameter of the first holder segment",
    )
    LH2 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the second holder segment"
    )
    DH2 = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        blank=True,
        null=True,
        help_text="Outside diameter of the second holder segment",
    )
    LH3 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the third holder segment"
    )
    DH3 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Outside diameter of the third holder segment"
    )
    author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=None, help_text="Author of the holder")

    def __str__(self):
        return self.holder_type_dict.get(self.holder_type, "Unknown holder type")

machines/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Machine(models.Model):
    name = models.CharField(max_length=100, help_text="Machine name")
    description = models.TextField(help_text="Machine description")
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, help_text="Author of the machine"
    )

    def get_absolute_url(self):
        return reverse("machine-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

tools/models.py
from django.contrib.auth.models import User
from django.db import models


class Tool(models.Model):
    tool_type_choices = [
        ("end_mill", "WALEC"),
        ("ball_nose", "KULA"),
        ("bull_nose", "WALEC_Z_R"),
        ("typer_ball_nose", "STOZKOWY"),
        ("engraving", "GRAWERKA"),
        ("drill", "WIERTŁO"),
    ]

    tool_type_dict = dict(tool_type_choices)

    tool_type = models.CharField(max_length=100, choices=tool_type_choices, help_text="Tool type")
    catalog_nr = models.CharField(max_length=100, help_text="Tool catalog number")
    R = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Corner radius of a end- and bull- mill"
    )
    L1 = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True, help_text="Blade length")
    D1 = models.DecimalField(max_digits=10, decimal_places=3, blank=True, null=True, help_text="Blade diameter")
    L2 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the first shaft segment"
    )
    D2 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Diameter of the first shaft segment"
    )
    L3 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the second shaft segment"
    )
    D3 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Diameter of the second shaft segment"
    )
    L4 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Length of the third shaft segment"
    )
    D4 = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Diameter of the third shaft segment"
    )
    author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default=None, help_text="Author of the tool")

    def __str__(self):
        return self.tool_type_dict.get(self.tool_type, "Unknown tool type")

tools_assembly/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from holders.models import Holder
from machines.models import Machine
from tools.models import Tool


class ToolAssembly(models.Model):
    tool_nr = models.PositiveIntegerField(help_text="Number of the tool assembly in machine table.")
    radius = models.DecimalField(
        max_digits=10, decimal_places=3, blank=True, null=True, help_text="Radius of the tool assembly."
    )
    total_length = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True, help_text="Total tool length."
    )
    outside_holder = models.DecimalField(
        max_digits=10, decimal_places=2, blank=True, null=True, help_text="Length outside the holder."
    )
    machine = models.ForeignKey(
        Machine,
        on_delete=models.SET_DEFAULT,
        default=None,
        related_name="tools",
        null=True,
        help_text="The machine to which the tool is assigned.",
    )
    holder = models.ForeignKey(
        Holder, on_delete=models.CASCADE, help_text="A holder component used in a tool assembly."
    )
    tool = models.ForeignKey(Tool, on_delete=models.CASCADE, help_text="A tool component used in a tool assembly.")
    author = models.ForeignKey(
        User,
        on_delete=models.SET_DEFAULT,
        default=None,
        help_text="Author of the tool assembly.",
    )

    def get_comments(self):
        return self.comments.order_by("-date_posted")


class UserComment(models.Model):
    content = models.TextField(help_text="User comment.")
    date_posted = models.DateTimeField(
        default=timezone.now, help_text="Date the comment was published <em>YYYY-MM-DD</em>."
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, help_text="Author of the user comment.")
    tool_assembly = models.ForeignKey(
        ToolAssembly,
        on_delete=models.CASCADE,
        related_name="comments",
        help_text="The tool assembly to which the comment is assigned.",
    )

machines/forms.py
from django import forms

from .models import Machine


class MachineForm(forms.ModelForm):
    class Meta:
        model = Machine
        fields = ["name", "description"]
        labels = {"name": "Nazwa maszyny", "description": "Opis maszyny"}

machines/views.py
import logging
from typing import Dict, List, Union

import pandas as pd
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .forms import MachineForm
from .models import Machine

# from weasyprint import HTML


logger = logging.getLogger(__name__)
Breadcrumb = Dict[str, Union[str, str]]


class BreadcrumbMixin:
    def get_context_data(self, **kwargs) -> Dict[str, Union[str, List[Breadcrumb]]]:
        context = super().get_context_data(**kwargs)
        context["breadcrumbs"] = self.get_breadcrumbs()
        return context

    def get_breadcrumbs(self) -> List[Breadcrumb]:
        breadcrumbs = [{"title": "Strona główna", "url": reverse("app-home")}]

        if isinstance(self, MachineDetailView):
            machine = self.get_object()
            breadcrumbs.append(
                {
                    "title": machine.name,
                    "url": reverse("machine-detail", kwargs={"pk": machine.pk}),
                }
            )
        elif isinstance(self, MachineCreateView):
            breadcrumbs.append({"title": "Utwórz nową maszynę", "url": reverse("machine-create")})
        elif isinstance(self, MachineUpdateView):
            machine = self.get_object()
            breadcrumbs.append(
                {
                    "title": machine.name,
                    "url": reverse("machine-detail", kwargs={"pk": machine.pk}),
                }
            )
            breadcrumbs.append(
                {
                    "title": "Aktualizuj",
                    "url": reverse("machine-update", kwargs={"pk": machine.pk}),
                }
            )

        return breadcrumbs


@login_required
def home(request: HttpRequest) -> HttpResponse:
    user = request.user
    logger.info(f"User {user} home view accessed.")
    return render(request, "machines/machine.html", {"title": "Home"})


class MachineListView(BreadcrumbMixin, ListView):
    model = Machine
    template_name = "machines/machines_list.html"

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        user = request.user
        logger.info(f"Machine List View accessed by user {user}")
        return super().get(request, *args, **kwargs)


class MachineDetailView(BreadcrumbMixin, DetailView):
    model = Machine
    template_name = "machines/machine_detail.html"

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        user = request.user
        logger.info(f"Machine Detail View accessed by user {user}")
        return super().get(request, *args, **kwargs)


class MachineCreateView(LoginRequiredMixin, BreadcrumbMixin, PermissionRequiredMixin, CreateView):
    permission_required = "machines.add_machine"
    model = Machine
    template_name = "machines/machine_form.html"
    form_class = MachineForm

    def form_valid(self, form: MachineForm) -> HttpResponse:
        form.instance.author = self.request.user
        logger.info(f"Machine {form.instance.name} created by {form.instance.author}.")
        return super().form_valid(form)


class MachineUpdateView(BreadcrumbMixin, LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = "machines.change_machine"
    model = Machine
    template_name = "machines/machine_form.html"
    fields = ["name", "description"]

    def form_valid(self, form: MachineForm) -> HttpResponse:
        form.instance.author = self.request.user
        logger.info(f"Machine {form.instance.name} updated by {form.instance.author}.")
        return super().form_valid(form)


class MachineDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    permission_required = "machines.delete_machine"
    model = Machine
    template_name = "machines/delete_confirm.html"
    success_url = "/"

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        machine = self.get_object()
        user = request.user
        logger.info(f"Machine {machine.name} deleted by user {user}")
        return super().post(request, *args, **kwargs)


def generate_csv(request: HttpRequest) -> HttpResponse:
    machines = Machine.objects.all()
    data = []

    for machine in machines:
        tools = machine.tools.all()
        for tool in tools:
            data.append(
                {
                    "Nr narzędzia": tool.tool_nr,
                    "Promień": tool.radius,
                    "Długość całkowita": tool.total_length,
                    "Długość poza oprawką": tool.outside_holder,
                    "Maszyna": machine.name,
                    "Typ oprawki": tool.holder.get_holder_type_display(),
                    "Typ freza": tool.tool.get_tool_type_display(),
                }
            )

    df = pd.DataFrame(data)
    response = HttpResponse(content_type="text/csv; charset=utf-8")
    response["Content-Disposition"] = 'attachment; filename="data-csv.csv"'
    csv_to_data = df.to_csv(None, index=False, encoding="utf-8")

    response.write(csv_to_data)

    logger.info(f"CSV generation completed by user: {request.user}")

    return response


# def generic_pdf(request: HttpRequest) -> HttpResponse:
#     os.add_dll_directory(r"C:\Program Files\GTK3-Runtime Win64\bin")
#
#     machines = Machine.objects.all()
#     data = []
#
#     for machine in machines:
#         tools = machine.tools.all()
#         for tool in tools:
#             data.append(
#                 {
#                     "tool_number": tool.tool_nr,
#                     "radius": tool.radius,
#                     "total_length": tool.total_length,
#                     "outside_holder": tool.outside_holder,
#                     "machine": machine.name,
#                     "holder_type_display": tool.holder.get_holder_type_display(),
#                     "tool_type_display": tool.tool.get_tool_type_display(),
#                 }
#             )
#
#     content = render_to_string("machines/root.html", {"machines": data})
#
#     with NamedTemporaryFile(delete=False, suffix=".pdf") as file:
#         HTML(string=content).write_pdf(file.name)
#
#         file.seek(0)
#         pdf_content = file.read()
#
#     response = HttpResponse(pdf_content, content_type="application/pdf")
#     response["Content-Disposition"] = 'inline; filename="generated.pdf"'
#
#     os.remove(file.name)
#
#     logger.info(f"PDF generation completed by user: {request.user}")
#
#     return response

machines/templates/machines/delete_confirm.html
{% extends "machines/index.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header"><h3 class="text-left font-weight-light my-4">{% blocktrans %} Delete machine {% endblocktrans %}</h3></div>
                <div class="content-section">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset class="form group">
                                <h3>{% blocktrans %} Are you sure you want to delete {% endblocktrans %}{{ object.name }}?</h3>
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-danger" type="submit">{% trans "Yes" %}</button>
                                <a class="btn btn-secondary" href="{% url 'machine-detail' object.id %}">{% trans "Cancel" %}</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

machines/templates/machines/index.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <meta name="keywords" content=" ">
        <title>Tools manager</title>
        <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="https://kit.fontawesome.com/2b939afadc.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{% url 'app-home' %}">Tools manager</a>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
                <div class="input-group">
{#                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />#}
{#                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>#}
                </div>
            </form>
            <!-- Navbar-->
                <style>
                    .custom-icon {
                        font-size: 20px;
                        color: #6c757d;
                        margin: 5px;
                    }
                </style>
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <ul>
                    {% if user_notifications.count > 0 %}
                        <span class="badge bg-danger">{{ user_notifications.count }}</span>
                    {% else %}
                        <span class="badge bg-danger">0</span>
                    {% endif %}
                </ul>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarNotification" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-regular fa-bell"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        {% for user_notification in user_notifications %}
                        <li><a class="dropdown-item" href="{% url 'unread-notifications' %}"> {{ user_notification.notification.message }}</a></li>
                        {% if not forloop.last %}
                        <div class="dropdown-divider"></div>
                        {% endif %}
                        {% endfor %}
                        <li><hr class="dropdown-divider" /></li>
                    </ul>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'profile' %}">{% trans "User profile" %}</a></li>
                        <li><hr class="dropdown-divider" /></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">{% trans "Logout" %}</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">{% trans "Main" %}</div>
                            <a class="nav-link" href="{% url 'app-home' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                {% trans "Main site" %}
                            </a>
                            <div class="sb-sidenav-menu-heading">{% trans "Machines & tools" %}</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                {% trans "Machines" %}
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    {% for machine in machines %}
                                    <a class="nav-link" href="{% url 'machine-detail' machine.pk %}">{{ machine.name }}</a>
                                    {% endfor %}

                                    {% if perms.machines.add_machine %}
                                    <a class="nav-link" href="{% url 'machine-create' %}">{% trans "Add machine" %}</a>
                                    {% endif %}
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                                <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                                {% trans "Tools" %}
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        {% trans "Mill Tool" %}
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="{% url 'tool' %}">{% trans "Mill tool table" %}</a>
                                            {% if perms.tools.add_tool %}
                                            <a class="nav-link" href="{% url 'tool-create' %}">{% trans "Add mill tool" %}</a>
                                            {% endif %}
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        {% trans "Holder" %}
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="{% url 'holder' %}">{% trans "Holder table" %}</a>
                                            {% if perms.holders.add_holder %}
                                            <a class="nav-link" href="{% url 'holder-create' %}">{% trans "Add holder" %}</a>
                                            {% endif %}
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseTool" aria-expanded="false" aria-controls="pagesCollapseError">
                                        {% trans "Tool assembly" %}
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseTool" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="{% url 'tool-assembly' %}">{% trans "Tool assembly table" %}</a>
                                            {% if perms.tools_assembly.add_toolassembly %}
                                            <a class="nav-link" href="{% url 'tool-assembly-create' %}">{% trans "Add tool assembly" %}</a>
                                            {% endif %}
                                        </nav>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer">
                        <div class="small">{% trans "Logged in as" %}:</div>
                        {{ user.username }}
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <style>
                        .breadcrumbs {
                            margin: 8px;
                        }
                    </style>
                    <div class="breadcrumbs container-fluid ">
                        {% for breadcrumb in breadcrumbs %}
                            <a href="{{ breadcrumb.url }}">{{ breadcrumb.title }}</a>
                            {% if not forloop.last %}&gt;{% endif %}
                        {% endfor %}
                    </div>
                    {% block content %}{% endblock content %}
                </div>
            </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid px-4">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright © Tools Manager 2023</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
    </body>
</html>

machines/templates/machines/machine.html
{% extends "machines/index.html" %}
{% load i18n %}
{% block content %}
  <h1 class="mt-4"></h1>
  <div class="row">
        {% for machine in machines %}
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary text-white mb-4">
                <div class="card-body">
                    <a class="text-white stretched-link" href="{% url 'machine-detail' machine.pk %}">{{ machine.name }}</a>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="{% url 'machine-detail' machine.pk %}">{% trans "Tools table" %}</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        {% endfor %}

        {% if perms.machines.add_machine %}
        <div class="col-xl-3 col-md-6">
            <div class="card bg-success text-white mb-4">
                <div class="card-body">
                    <a class="text-white stretched-link" href="{% url 'machine-create' %}">{% trans "Add machine" %}</a>
                </div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="{% url 'machine-create' %}"></a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        {% endif %}
  </div>
{% endblock content %}